// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wprphfrmvatpzxdoaxug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwcnBoZnJtdmF0cHp4ZG9heHVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDU5MDMsImV4cCI6MjA2NzEyMTkwM30.VSpzD9_NnKmXsVSfEgOjp-N6Y-Z9NR0peFYdXqMAPWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});